[package]
name = "catplay_iap2_client"
version = "0.1.0"
edition = "2024"

[dependencies]
catplay_csm = { path = "../../core/catplay_csm" }
catplay_iap2_link = { path = "../../core/catplay_iap2_link" }
catplay_mfi = { path = "../../core/catplay_mfi", optional = true }
catplay_util = { path = "../../core/catplay_util" }

async-trait = "0.1.89"
log = "0.4.28"
thiserror = "2.0.17"
bytes = "1.10.1"
macaddr = "1.0.1"
libc = "0.2"

tokio = { version = "1.48.0", features = [
    "rt",
    "macros",
    "time",
    "net",
    "io-util",
], optional = true }
tokio-util = { version = "0.7.15", features = ["codec", "rt"], optional = true }
futures = { version = "0.3.31", optional = true }

[dev-dependencies]
ctor = "0.4.2"
mockall = "0.13.1"

[features]
tokio = ["dep:tokio", "dep:tokio-util", "dep:futures"]
mfi = ["dep:catplay_mfi"]

default = ["tokio", "mfi"]
