[package]
name = "catplay_carplay_tx_gadget"
version = "0.1.0"
edition = "2024"

[dependencies]
catplay_iap2_usb_host = { path = "../usb/catplay_iap2_usb_host" }
catplay_iap2_usb = { path = "../usb/catplay_iap2_usb" }
catplay_iap2_client = { path = "../async/catplay_iap2_client" }
catplay_util = { path = "../core/catplay_util" }
catplay_tracing = { path = "../core/catplay_tracing" }
catplay_hap = { path = "../core/catplay_hap" }
catplay_bonjour = { path = "../core/catplay_bonjour" }
catplay_carplay = { path = "../carplay/catplay_carplay" }
catplay_csm = { path = "../core/catplay_csm" }

async-trait = "0.1.89"
tokio = { version = "1.48.0", features = ["rt", "signal"] }
log = "0.4.28"
futures = "0.3.31"
thiserror = "2.0.17"

[dev-dependencies]
catplay_carplay_rx_gadget = { path = "../catplay_carplay_rx_gadget" }
