// Refer to https://github.com/torvalds/linux/blob/master/include/net/bluetooth/mgmt.h

use std::fmt;

// Bluetooth mgmt opcodes
pub const MGMT_INDEX_HCI0: u16 = 0; // for hci0
pub const MGMT_INDEX_NONE: u16 = 0xffff; // all adapters

// Bluetooth socket constants
pub const AF_BLUETOOTH: i32 = 31;
pub const BTPROTO_HCI: i32 = 1;
pub const HCI_CHANNEL_CONTROL: u16 = 3;

#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MgmtEv {
    CmdComplete              = 0x0001,
    CmdStatus                = 0x0002,
    ControllerError          = 0x0003,
    IndexAdded               = 0x0004,
    IndexRemoved             = 0x0005,
    NewSettings              = 0x0006,
    ClassOfDevChanged        = 0x0007,
    LocalNameChanged         = 0x0008,
    NewLinkKey               = 0x0009,
    NewLongTermKey           = 0x000A,
    DeviceConnected          = 0x000B,
    DeviceDisconnected       = 0x000C,
    ConnectFailed            = 0x000D,
    PinCodeRequest           = 0x000E,
    UserConfirmRequest       = 0x000F,
    UserPasskeyRequest       = 0x0010,
    AuthFailed               = 0x0011,
    DeviceFound              = 0x0012,
    Discovering              = 0x0013,
    DeviceBlocked            = 0x0014,
    DeviceUnblocked          = 0x0015,
    DeviceUnpaired           = 0x0016,
    PasskeyNotify            = 0x0017,
    NewIrk                   = 0x0018,
    NewCsrk                  = 0x0019,
    DeviceAdded              = 0x001A,
    DeviceRemoved            = 0x001B,
    NewConnParam             = 0x001C,
    UnconfIndexAdded         = 0x001D,
    UnconfIndexRemoved       = 0x001E,
    NewConfigOptions         = 0x001F,
    ExtIndexAdded            = 0x0020,
    ExtIndexRemoved          = 0x0021,
    LocalOobDataUpdated      = 0x0022,
    AdvertisingAdded         = 0x0023,
    AdvertisingRemoved       = 0x0024,
    ExtInfoChanged           = 0x0025,
    PhyConfigurationChanged  = 0x0026,
    ExpFeatureChanged        = 0x0027,
    DeviceFlagsChanged       = 0x002A,
    AdvMonitorAdded          = 0x002B,
    AdvMonitorRemoved        = 0x002C,
    ControllerSuspend        = 0x002D,
    ControllerResume         = 0x002E,
    AdvMonitorDeviceFound    = 0x002F,
    AdvMonitorDeviceLost     = 0x0030,
    MeshDeviceFound          = 0x0031,
    MeshPacketComplete       = 0x0032,
    Unknown(u16),
}

impl From<u16> for MgmtEv {
    fn from(value: u16) -> Self {
        use MgmtEv::*;
        match value {
            0x0001 => CmdComplete,
            0x0002 => CmdStatus,
            0x0003 => ControllerError,
            0x0004 => IndexAdded,
            0x0005 => IndexRemoved,
            0x0006 => NewSettings,
            0x0007 => ClassOfDevChanged,
            0x0008 => LocalNameChanged,
            0x0009 => NewLinkKey,
            0x000A => NewLongTermKey,
            0x000B => DeviceConnected,
            0x000C => DeviceDisconnected,
            0x000D => ConnectFailed,
            0x000E => PinCodeRequest,
            0x000F => UserConfirmRequest,
            0x0010 => UserPasskeyRequest,
            0x0011 => AuthFailed,
            0x0012 => DeviceFound,
            0x0013 => Discovering,
            0x0014 => DeviceBlocked,
            0x0015 => DeviceUnblocked,
            0x0016 => DeviceUnpaired,
            0x0017 => PasskeyNotify,
            0x0018 => NewIrk,
            0x0019 => NewCsrk,
            0x001A => DeviceAdded,
            0x001B => DeviceRemoved,
            0x001C => NewConnParam,
            0x001D => UnconfIndexAdded,
            0x001E => UnconfIndexRemoved,
            0x001F => NewConfigOptions,
            0x0020 => ExtIndexAdded,
            0x0021 => ExtIndexRemoved,
            0x0022 => LocalOobDataUpdated,
            0x0023 => AdvertisingAdded,
            0x0024 => AdvertisingRemoved,
            0x0025 => ExtInfoChanged,
            0x0026 => PhyConfigurationChanged,
            0x0027 => ExpFeatureChanged,
            0x002A => DeviceFlagsChanged,
            0x002B => AdvMonitorAdded,
            0x002C => AdvMonitorRemoved,
            0x002D => ControllerSuspend,
            0x002E => ControllerResume,
            0x002F => AdvMonitorDeviceFound,
            0x0030 => AdvMonitorDeviceLost,
            0x0031 => MeshDeviceFound,
            0x0032 => MeshPacketComplete,
            other => Unknown(other),
        }
    }
}

impl fmt::Display for MgmtEv {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            MgmtEv::Unknown(code) => write!(f, "Unknown(0x{:04X})", code),
            _ => write!(f, "{:?}", self),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MgmtStatus {
    Success = 0x00,
    UnknownCommand = 0x01,
    NotConnected = 0x02,
    Failed = 0x03,
    ConnectFailed = 0x04,
    AuthFailed = 0x05,
    NotPaired = 0x06,
    NoResources = 0x07,
    Timeout = 0x08,
    AlreadyConnected = 0x09,
    Busy = 0x0a,
    Rejected = 0x0b,
    NotSupported = 0x0c,
    InvalidParams = 0x0d,
    Disconnected = 0x0e,
    NotPowered = 0x0f,
    Cancelled = 0x10,
    InvalidIndex = 0x11,
    RFKilled = 0x12,
    AlreadyPaired = 0x13,
    PermissionDenied = 0x14,
    Unknown(u8),
}
impl From<u8> for MgmtStatus {
    fn from(code: u8) -> Self {
        match code {
            0x00 => MgmtStatus::Success,
            0x01 => MgmtStatus::UnknownCommand,
            0x02 => MgmtStatus::NotConnected,
            0x03 => MgmtStatus::Failed,
            0x04 => MgmtStatus::ConnectFailed,
            0x05 => MgmtStatus::AuthFailed,
            0x06 => MgmtStatus::NotPaired,
            0x07 => MgmtStatus::NoResources,
            0x08 => MgmtStatus::Timeout,
            0x09 => MgmtStatus::AlreadyConnected,
            0x0a => MgmtStatus::Busy,
            0x0b => MgmtStatus::Rejected,
            0x0c => MgmtStatus::NotSupported,
            0x0d => MgmtStatus::InvalidParams,
            0x0e => MgmtStatus::Disconnected,
            0x0f => MgmtStatus::NotPowered,
            0x10 => MgmtStatus::Cancelled,
            0x11 => MgmtStatus::InvalidIndex,
            0x12 => MgmtStatus::RFKilled,
            0x13 => MgmtStatus::AlreadyPaired,
            0x14 => MgmtStatus::PermissionDenied,
            other => MgmtStatus::Unknown(other),
        }
    }
}

impl std::fmt::Display for MgmtStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let desc = match self {
            MgmtStatus::Success => "Success",
            MgmtStatus::UnknownCommand => "Unknown command",
            MgmtStatus::NotConnected => "Not connected",
            MgmtStatus::Failed => "Failed",
            MgmtStatus::ConnectFailed => "Connect failed",
            MgmtStatus::AuthFailed => "Authentication failed",
            MgmtStatus::NotPaired => "Not paired",
            MgmtStatus::NoResources => "No resources",
            MgmtStatus::Timeout => "Timeout",
            MgmtStatus::AlreadyConnected => "Already connected",
            MgmtStatus::Busy => "Busy",
            MgmtStatus::Rejected => "Rejected",
            MgmtStatus::NotSupported => "Not supported",
            MgmtStatus::InvalidParams => "Invalid parameters",
            MgmtStatus::Disconnected => "Disconnected",
            MgmtStatus::NotPowered => "Not powered",
            MgmtStatus::Cancelled => "Cancelled",
            MgmtStatus::InvalidIndex => "Invalid index",
            MgmtStatus::RFKilled => "RFKILLED (blocked by rfkill)",
            MgmtStatus::AlreadyPaired => "Already paired",
            MgmtStatus::PermissionDenied => "Permission denied",
            MgmtStatus::Unknown(code) => return write!(f, "Unknown (0x{:02x})", code),
        };
        write!(f, "{}", desc)
    }
}

#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MgmtOp {
    ReadCommands             = 0x0002,
    ReadIndexList            = 0x0003,
    ReadInfo                 = 0x0004,
    SetPowered               = 0x0005,
    SetDiscoverable          = 0x0006,
    SetConnectable           = 0x0007,
    SetFastConnectable       = 0x0008,
    SetBondable              = 0x0009,
    SetLinkSecurity          = 0x000A,
    SetSsp                   = 0x000B,
    SetHs                    = 0x000C,
    SetLe                    = 0x000D,
    SetDevClass              = 0x000E,
    SetLocalName             = 0x000F,
    AddUuid                  = 0x0010,
    RemoveUuid               = 0x0011,
    LoadLinkKeys             = 0x0012,
    LoadLongTermKeys         = 0x0013,
    Disconnect               = 0x0014,
    GetConnections           = 0x0015,
    PinCodeReply             = 0x0016,
    PinCodeNegReply          = 0x0017,
    SetIoCapability          = 0x0018,
    PairDevice               = 0x0019,
    CancelPairDevice         = 0x001A,
    UnpairDevice             = 0x001B,
    UserConfirmReply         = 0x001C,
    UserConfirmNegReply      = 0x001D,
    UserPasskeyReply         = 0x001E,
    UserPasskeyNegReply      = 0x001F,
    ReadLocalOobData         = 0x0020,
    AddRemoteOobData         = 0x0021,
    RemoveRemoteOobData      = 0x0022,
    StartDiscovery           = 0x0023,
    StopDiscovery            = 0x0024,
    ConfirmName              = 0x0025,
    BlockDevice              = 0x0026,
    UnblockDevice            = 0x0027,
    SetDeviceId              = 0x0028,
    SetAdvertising           = 0x0029,
    SetBredr                 = 0x002A,
    SetStaticAddress         = 0x002B,
    SetScanParams            = 0x002C,
    SetSecureConn            = 0x002D,
    SetDebugKeys             = 0x002E,
    SetPrivacy               = 0x002F,
    LoadIrks                 = 0x0030,
    GetConnInfo              = 0x0031,
    GetClockInfo             = 0x0032,
    AddDevice                = 0x0033,
    RemoveDevice             = 0x0034,
    LoadConnParam            = 0x0035,
    ReadUnconfIndexList      = 0x0036,
    ReadConfigInfo           = 0x0037,
    SetExternalConfig        = 0x0038,
    SetPublicAddress         = 0x0039,
    StartServiceDiscovery    = 0x003A,
    ReadLocalOobExtData      = 0x003B,
    ReadExtIndexList         = 0x003C,
    ReadAdvFeatures          = 0x003D,
    AddAdvertising           = 0x003E,
    RemoveAdvertising        = 0x003F,
    GetAdvSizeInfo           = 0x0040,
    StartLimitedDiscovery    = 0x0041,
    ReadExtInfo              = 0x0042,
    SetAppearance            = 0x0043,
    GetPhyConfiguration      = 0x0044,
    SetPhyConfiguration      = 0x0045,
    SetBlockedKeys           = 0x0046,
    SetWidebandSpeech        = 0x0047,
    ReadControllerCap        = 0x0048,
    ReadExpFeaturesInfo      = 0x0049,
    SetExpFeature            = 0x004A,
    ReadDefSystemConfig      = 0x004B,
    SetDefSystemConfig       = 0x004C,
    ReadDefRuntimeConfig     = 0x004D,
    SetDefRuntimeConfig      = 0x004E,
    GetDeviceFlags           = 0x004F,
    SetDeviceFlags           = 0x0050,
    ReadAdvMonitorFeatures   = 0x0051,
    AddAdvPatternsMonitor    = 0x0052,
    RemoveAdvMonitor         = 0x0053,
    AddExtAdvParams          = 0x0054,
    AddExtAdvData            = 0x0055,
    AddAdvPatternsMonitorRssi= 0x0056,
    SetMeshReceiver          = 0x0057,
    MeshReadFeatures         = 0x0058,
    MeshSend                 = 0x0059,
    MeshSendCancel           = 0x005A,
    HciCmdSync               = 0x005B,
}

#[repr(C)]
pub struct SockAddrHci {
    pub family: libc::sa_family_t,
    pub dev: u16,
    pub channel: u16,
}
