#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum HttpStatus {
    Continue = 100,
    SwitchingProtocols = 101,
    Processing = 102,
    Checkpoint = 103,

    Ok = 200,
    Created = 201,
    Accepted = 202,
    NonAuthoritativeInformation = 203,
    NoContent = 204,
    ResetContent = 205,
    PartialContent = 206,
    MultiStatus = 207,
    AlreadyReported = 208,
    ContentDifferent = 210,
    IMUsed = 226,
    LowOnStorageSpace = 250,

    MultipleChoices = 300,
    MovedPermanently = 301,
    Found = 302,
    SeeOther = 303,
    NotModified = 304,
    UseProxy = 305,
    SwitchProxy = 306,
    TemporaryRedirect = 307,
    PermanentRedirect = 308,
    MovedLocation = 330,
    GoingAway = 350,
    LoadBalancing = 351,

    BadRequest = 400,
    Unauthorized = 401,
    PaymentRequired = 402,
    Forbidden = 403,
    NotFound = 404,
    MethodNotAllowed = 405,
    NotAcceptable = 406,
    ProxyAuthRequired = 407,
    RequestTimeout = 408,
    Conflict = 409,
    Gone = 410,
    LengthRequired = 411,
    PreconditionFailed = 412,
    RequestEntityTooLarge = 413,
    RequestURITooLong = 414,
    UnsupportedMediaType = 415,
    RequestedRangeNotSatisfiable = 416,
    ExpectationFailed = 417,
    ImATeapot = 418,
    AuthTimeout = 419,
    EnhanceYourCalm = 420,
    NotAuthoritative = 421,
    UnprocessableEntity = 422,
    ExpectationFailedAlt = 423,
    FailedDependency = 424,
    UnorderedCollection = 425,
    UpgradeRequired = 426,
    PreconditionRequired = 428,
    TooManyRequests = 429,
    HeaderFieldsTooLarge = 431,
    LoginTimeout = 440,
    NoResponse = 444,
    RetryWith = 449,
    BlockedByParentalControls = 450,
    ParamNotUnderstood = 451,
    ConferenceNotFound = 452,
    NotEnoughBandwidth = 453,
    SessionNotFound = 454,
    MethodNotValid = 455,
    HeaderFieldNotValid = 456,
    InvalidRange = 457,
    ParamReadOnly = 458,
    AggregateOpNotAllowed = 459,
    OnlyAggregateOpAllowed = 460,
    UnsupportedTransport = 461,
    DestinationUnreachable = 462,
    DestinationProhibited = 463,
    TransportNotReady = 464,
    UnknownNotificationReason = 465,
    KeyManagementError = 466,
    ConnectionAuthRequired = 470,
    ConnectionCredentialsRejected = 471,
    SecureConnectionFailure = 472,
    InvalidCollblob = 475,
    ClientClosedRequest = 499,

    InternalServerError = 500,
    NotImplemented = 501,
    BadGateway = 502,
    ServiceUnavailable = 503,
    GatewayTimeout = 504,
    VersionNotSupported = 505,
    VariantAlsoNegotiates = 506,
    InsufficientStorage = 507,
    LoopDetected = 508,
    BandwidthLimitExceeded = 509,
    NotExtended = 510,
    NetworkAuthRequired = 511,
    OriginError = 520,
    ConnectionTimedOut = 522,
    ProxyDeclinedRequest = 523,
    TimeoutOccurred = 524,
    OptionNotSupported = 551,
    ProxyUnavailable = 553,
    NetworkReadTimeout = 598,
    NetworkConnectTimeout = 599,

    Unknown(u16),
}

impl HttpStatus {
    pub fn from_code(code: u16) -> Self {
        use HttpStatus::*;
        match code {
            100 => Continue,
            101 => SwitchingProtocols,
            102 => Processing,
            103 => Checkpoint,

            200 => Ok,
            201 => Created,
            202 => Accepted,
            203 => NonAuthoritativeInformation,
            204 => NoContent,
            205 => ResetContent,
            206 => PartialContent,
            207 => MultiStatus,
            208 => AlreadyReported,
            210 => ContentDifferent,
            226 => IMUsed,
            250 => LowOnStorageSpace,

            300 => MultipleChoices,
            301 => MovedPermanently,
            302 => Found,
            303 => SeeOther,
            304 => NotModified,
            305 => UseProxy,
            306 => SwitchProxy,
            307 => TemporaryRedirect,
            308 => PermanentRedirect,
            330 => MovedLocation,
            350 => GoingAway,
            351 => LoadBalancing,

            400 => BadRequest,
            401 => Unauthorized,
            402 => PaymentRequired,
            403 => Forbidden,
            404 => NotFound,
            405 => MethodNotAllowed,
            406 => NotAcceptable,
            407 => ProxyAuthRequired,
            408 => RequestTimeout,
            409 => Conflict,
            410 => Gone,
            411 => LengthRequired,
            412 => PreconditionFailed,
            413 => RequestEntityTooLarge,
            414 => RequestURITooLong,
            415 => UnsupportedMediaType,
            416 => RequestedRangeNotSatisfiable,
            417 => ExpectationFailed,
            418 => ImATeapot,
            419 => AuthTimeout,
            420 => EnhanceYourCalm,
            421 => NotAuthoritative,
            422 => UnprocessableEntity,
            423 => ExpectationFailedAlt,
            424 => FailedDependency,
            425 => UnorderedCollection,
            426 => UpgradeRequired,
            428 => PreconditionRequired,
            429 => TooManyRequests,
            431 => HeaderFieldsTooLarge,
            440 => LoginTimeout,
            444 => NoResponse,
            449 => RetryWith,
            450 => BlockedByParentalControls,
            451 => ParamNotUnderstood,
            452 => ConferenceNotFound,
            453 => NotEnoughBandwidth,
            454 => SessionNotFound,
            455 => MethodNotValid,
            456 => HeaderFieldNotValid,
            457 => InvalidRange,
            458 => ParamReadOnly,
            459 => AggregateOpNotAllowed,
            460 => OnlyAggregateOpAllowed,
            461 => UnsupportedTransport,
            462 => DestinationUnreachable,
            463 => DestinationProhibited,
            464 => TransportNotReady,
            465 => UnknownNotificationReason,
            466 => KeyManagementError,
            470 => ConnectionAuthRequired,
            471 => ConnectionCredentialsRejected,
            472 => SecureConnectionFailure,
            475 => InvalidCollblob,
            499 => ClientClosedRequest,

            500 => InternalServerError,
            501 => NotImplemented,
            502 => BadGateway,
            503 => ServiceUnavailable,
            504 => GatewayTimeout,
            505 => VersionNotSupported,
            506 => VariantAlsoNegotiates,
            507 => InsufficientStorage,
            508 => LoopDetected,
            509 => BandwidthLimitExceeded,
            510 => NotExtended,
            511 => NetworkAuthRequired,
            520 => OriginError,
            522 => ConnectionTimedOut,
            523 => ProxyDeclinedRequest,
            524 => TimeoutOccurred,
            551 => OptionNotSupported,
            553 => ProxyUnavailable,
            598 => NetworkReadTimeout,
            599 => NetworkConnectTimeout,

            other => Unknown(other),
        }
    }

    pub fn as_code(&self) -> u16 {
        use HttpStatus::*;
        match self {
            Continue => 100,
            SwitchingProtocols => 101,
            Processing => 102,
            Checkpoint => 103,

            Ok => 200,
            Created => 201,
            Accepted => 202,
            NonAuthoritativeInformation => 203,
            NoContent => 204,
            ResetContent => 205,
            PartialContent => 206,
            MultiStatus => 207,
            AlreadyReported => 208,
            ContentDifferent => 210,
            IMUsed => 226,
            LowOnStorageSpace => 250,

            MultipleChoices => 300,
            MovedPermanently => 301,
            Found => 302,
            SeeOther => 303,
            NotModified => 304,
            UseProxy => 305,
            SwitchProxy => 306,
            TemporaryRedirect => 307,
            PermanentRedirect => 308,
            MovedLocation => 330,
            GoingAway => 350,
            LoadBalancing => 351,

            BadRequest => 400,
            Unauthorized => 401,
            PaymentRequired => 402,
            Forbidden => 403,
            NotFound => 404,
            MethodNotAllowed => 405,
            NotAcceptable => 406,
            ProxyAuthRequired => 407,
            RequestTimeout => 408,
            Conflict => 409,
            Gone => 410,
            LengthRequired => 411,
            PreconditionFailed => 412,
            RequestEntityTooLarge => 413,
            RequestURITooLong => 414,
            UnsupportedMediaType => 415,
            RequestedRangeNotSatisfiable => 416,
            ExpectationFailed => 417,
            ImATeapot => 418,
            AuthTimeout => 419,
            EnhanceYourCalm => 420,
            NotAuthoritative => 421,
            UnprocessableEntity => 422,
            ExpectationFailedAlt => 423,
            FailedDependency => 424,
            UnorderedCollection => 425,
            UpgradeRequired => 426,
            PreconditionRequired => 428,
            TooManyRequests => 429,
            HeaderFieldsTooLarge => 431,
            LoginTimeout => 440,
            NoResponse => 444,
            RetryWith => 449,
            BlockedByParentalControls => 450,
            ParamNotUnderstood => 451,
            ConferenceNotFound => 452,
            NotEnoughBandwidth => 453,
            SessionNotFound => 454,
            MethodNotValid => 455,
            HeaderFieldNotValid => 456,
            InvalidRange => 457,
            ParamReadOnly => 458,
            AggregateOpNotAllowed => 459,
            OnlyAggregateOpAllowed => 460,
            UnsupportedTransport => 461,
            DestinationUnreachable => 462,
            DestinationProhibited => 463,
            TransportNotReady => 464,
            UnknownNotificationReason => 465,
            KeyManagementError => 466,
            ConnectionAuthRequired => 470,
            ConnectionCredentialsRejected => 471,
            SecureConnectionFailure => 472,
            InvalidCollblob => 475,
            ClientClosedRequest => 499,

            InternalServerError => 500,
            NotImplemented => 501,
            BadGateway => 502,
            ServiceUnavailable => 503,
            GatewayTimeout => 504,
            VersionNotSupported => 505,
            VariantAlsoNegotiates => 506,
            InsufficientStorage => 507,
            LoopDetected => 508,
            BandwidthLimitExceeded => 509,
            NotExtended => 510,
            NetworkAuthRequired => 511,
            OriginError => 520,
            ConnectionTimedOut => 522,
            ProxyDeclinedRequest => 523,
            TimeoutOccurred => 524,
            OptionNotSupported => 551,
            ProxyUnavailable => 553,
            NetworkReadTimeout => 598,
            NetworkConnectTimeout => 599,

            Unknown(code) => *code,
        }
    }

    pub fn as_code_str(&self) -> [u8; 3] {
        let code = self.as_code();
        let mut buf = [0u8; 3];
        buf[0] = b'0' + (((code / 100) % 10) as u8);
        buf[1] = b'0' + (((code / 10) % 10) as u8);
        buf[2] = b'0' + ((code % 10) as u8);
        buf
    }

    pub fn reason_phrase(&self) -> &'static str {
        use HttpStatus::*;
        match self {
            Continue => "Continue",
            SwitchingProtocols => "Switching Protocols",
            Processing => "Processing",
            Checkpoint => "Checkpoint",

            Ok => "OK",
            Created => "Created",
            Accepted => "Accepted",
            NonAuthoritativeInformation => "Non-Authoritative Information",
            NoContent => "No Content",
            ResetContent => "Reset Content",
            PartialContent => "Partial Content",
            MultiStatus => "Multi-Status",
            AlreadyReported => "Already Reported",
            ContentDifferent => "Content Different",
            IMUsed => "IM Used",
            LowOnStorageSpace => "Low on Storage Space",

            MultipleChoices => "Multiple Choices",
            MovedPermanently => "Moved Permanently",
            Found => "Found",
            SeeOther => "See Other",
            NotModified => "Not Modified",
            UseProxy => "Use Proxy",
            SwitchProxy => "Switch Proxy",
            TemporaryRedirect => "Temporary Redirect",
            PermanentRedirect => "Permanent Redirect",
            MovedLocation => "Moved Location",
            GoingAway => "Going Away",
            LoadBalancing => "Load Balancing",

            BadRequest => "Bad Request",
            Unauthorized => "Unauthorized",
            PaymentRequired => "Payment Required",
            Forbidden => "Forbidden",
            NotFound => "Not Found",
            MethodNotAllowed => "Method Not Allowed",
            NotAcceptable => "Not Acceptable",
            ProxyAuthRequired => "Proxy Authentication Required",
            RequestTimeout => "Request Timeout",
            Conflict => "Conflict",
            Gone => "Gone",
            LengthRequired => "Length Required",
            PreconditionFailed => "Precondition Failed",
            RequestEntityTooLarge => "Request Entity Too Large",
            RequestURITooLong => "Request URI Too Long",
            UnsupportedMediaType => "Unsupported Media Type",
            RequestedRangeNotSatisfiable => "Requested Range Not Satisfiable",
            ExpectationFailed => "Expectation Failed",
            ImATeapot => "I'm a teapot",
            AuthTimeout => "Authentication Timeout",
            EnhanceYourCalm => "Enhance Your Calm",
            NotAuthoritative => "Not Authoritative",
            UnprocessableEntity => "Unprocessable Entity",
            ExpectationFailedAlt => "Expectation Failed",
            FailedDependency => "Failed Dependency",
            UnorderedCollection => "Unordered Collection",
            UpgradeRequired => "Upgrade Required",
            PreconditionRequired => "Precondition Required",
            TooManyRequests => "Too Many Requests",
            HeaderFieldsTooLarge => "Request Header Fields Too Large",
            LoginTimeout => "Login Timeout",
            NoResponse => "No Response",
            RetryWith => "Retry With",
            BlockedByParentalControls => "Blocked by Parental Controls",
            ParamNotUnderstood => "Parameter Not Understood",
            ConferenceNotFound => "Conference Not Found",
            NotEnoughBandwidth => "Not Enough Bandwidth",
            SessionNotFound => "Session Not Found",
            MethodNotValid => "Method Not Valid In This State",
            HeaderFieldNotValid => "Header Field Not Valid",
            InvalidRange => "Invalid Range",
            ParamReadOnly => "Parameter Is Read-Only",
            AggregateOpNotAllowed => "Aggregate Operation Not Allowed",
            OnlyAggregateOpAllowed => "Only Aggregate Operation Allowed",
            UnsupportedTransport => "Unsupported Transport",
            DestinationUnreachable => "Destination Unreachable",
            DestinationProhibited => "Destination Prohibited",
            TransportNotReady => "Data Transport Not Ready Yet",
            UnknownNotificationReason => "Notification Reason Unknown",
            KeyManagementError => "Key Management Error",
            ConnectionAuthRequired => "Connection Authorization Required",
            ConnectionCredentialsRejected => "Connection Credentials not accepted",
            SecureConnectionFailure => "Failure to establish secure connection",
            InvalidCollblob => "Invalid collblob",
            ClientClosedRequest => "Client Closed Request",

            InternalServerError => "Internal Server Error",
            NotImplemented => "Not Implemented",
            BadGateway => "Bad Gateway",
            ServiceUnavailable => "Service Unavailable",
            GatewayTimeout => "Gateway Timeout",
            VersionNotSupported => "Version Not Supported",
            VariantAlsoNegotiates => "Variant Also Negotiates",
            InsufficientStorage => "Insufficient Storage",
            LoopDetected => "Loop Detected",
            BandwidthLimitExceeded => "Bandwidth Limit Exceeded",
            NotExtended => "Not Extended",
            NetworkAuthRequired => "Network Authentication Required",
            OriginError => "Origin Error",
            ConnectionTimedOut => "Connection timed out",
            ProxyDeclinedRequest => "Proxy Declined Request",
            TimeoutOccurred => "Timeout occurred",
            OptionNotSupported => "Option Not Supported",
            ProxyUnavailable => "Proxy Unavailable",
            NetworkReadTimeout => "Network Read Timeout",
            NetworkConnectTimeout => "Network Connect Timeout",

            Unknown(_) => "",
        }
    }
}

impl std::fmt::Display for HttpStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{} ({})", self.as_code(), self.reason_phrase())
    }
}
